version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: ./restaurants-be
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./restaurants-fe
    ports:
      - "3000:80"
    env_file:
      - ./restaurants-fe/.env
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local
